### ISSUE TITLE
My Profile page enhancements

### ISSUE THREAD

**Issue by erik-rosa** [harlsh/leechcode#69]
Add user role to authentication 
Implement dashboard that shows a list of the problems the user has attempted and whether or not they solved it

**Comment by erik-rosa** [comment]
User role has been added and the setup for the table is there, we just need to store the problems a user has saved to the db

**Comment by harlsh** [comment]
Hey Eric,
I'm saving the users uid in our databases with the corresponding submission.
I also made an endpoint to view a users submission. It's  `http://localhost:8080/api/v1/submissions/<uid>`
You just need to fix this small problem here.
![image](https://user-images.githubusercontent.com/20385352/163902294-71df4923-9700-4959-a5ec-4c91c6068582.png)
In the above image, just make sure to parse the uid out of that localStorage string.

**Comment by erik-rosa** [comment]
uid parse complete with commit https://github.com/harlsh/leechcode/commit/9105c1ddc730664024e3a8bbeb2c6dd287156fde

**Comment by erik-rosa** [comment]
completed with commit https://github.com/harlsh/leechcode/commit/5a5c6fe2ef9fc3428808145a9d2c65c9d725fe35
